apiVersion: v1
data:
  argo.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIFJzCCAw+gAwIBAgIRAOop0OKmqBQhpQ3wOKkn4dQwDQYJKoZIhvcNAQELBQAw
    gYUxCzAJBgNVBAYTAkdCMQ8wDQYDVQQKDAZWb25hZ2UxGjAYBgNVBAsMEU5leG1v
    IEVuZ2luZWVyaW5nMQ8wDQYDVQQIDAZMb25kb24xJzAlBgNVBAMMHk5leG1vIElu
    dGVybmFsIENBIC0gVlBOIExvbmRvbjEPMA0GA1UEBwwGTG9uZG9uMB4XDTIwMTAw
    NzEwMzA1NFoXDTIxMTEwNzExMzA1NFowHjEcMBoGA1UEAwwTZ3JhZmFuYTAxLm5l
    eG1vLnh4eDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALnJx+8BKea4
    /jIzzlEvmiIbwPT0lTsn+BQHHtyh2s2RFiJGoST8IEx3vAYXk1ZUthyP52vzLbWN
    mZi+J80LQpK6kSaO+z4y/Th7BgN4JEeFtQ4/GtGUpYL2MPq+HcBjyJPY/m5lIxI0
    BCU4hWY+10gBM/SlWRtFKzVfUbIuw8xp3QW4qf+PaLZWdtvfbtlrqFADnUuB1mnY
    vxlw94FX9rHJou1nE1VJx6XRCBlhigwXHEFx1qCLhCxuYVxfc+yXl7x7Xq13JAM5
    u45fpwaopyJIPAixaeqXRkz7K+xeJEHe97xMwSBPTGitZXnoL2PXMwjqpTszjYik
    EmRFcoNHXx0CAwEAAaOB9zCB9DAeBgNVHREEFzAVghNncmFmYW5hMDEubmV4bW8u
    eHh4MAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUDn3TnBtgbGu0lLL0XNauUr8nJZUw
    HQYDVR0OBBYEFBeWVgPMEDHWWxNh2HP7sniXRVJnMA4GA1UdDwEB/wQEAwIFoDAd
    BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwWAYDVR0fBFEwTzBNoEugSYZH
    aHR0cDovL2NybC12cG4ubmV4bW8uY2xvdWQvY3JsLzI2NzE3MzBiLTVkMzItNDdi
    YS1hNzQwLWE4ZWI3ZGI4Yjc1NC5jcmwwDQYJKoZIhvcNAQELBQADggIBABwxnKMD
    4hNhB3LS4PUyVA/7uFjssgaBZQv9cojGoaNJP5JrnDfdoyyT+QZKIdjtQ39OZmhs
    SFgbo+A6WWm/Q4N3gmjuiFCrbjCAMNs1v+z9+SzTFFIMJJc9D/Bbmooj6f+Ix3CR
    2QDsQLaqE/G59Nz2BknpYnp8S3MlOGb4+pw5g6DhUIW1Mmgio22xwgsVEzHjLtkI
    9YFn/3QZEV0luftOpzGOPfTwDl4wAS0Je3S4pCLLM6XBAJsHibTcWCoQLl6drpny
    Kbzd2AXruBloOdPQSTtpguD4AAE7q276CSL7hNPbBUv5Hwr+4BmQVvfyokL3H5Aa
    Y8Hzt1PZK5fguPGGoW1WKAp93KwSZpKWA95OoiV0Caw1YXqhulj25FcsmzIL/hKt
    G92+TxMUoVbYKdoNJ1C0mwBnVGX+8hoMZ7JymT1zMtVY3kUo4+7fZMhWgHY78atm
    GtWZI3RSXumLfvFRnnAmAyHWwikB2LCOXb5PL3uG8frsSxDMySVh10JnwbXQE3Ry
    LIoQ8ZuBHhv/66tTpkD8ndJJ6uhGFIOyjzTEnE+yPqKqRExP1qxYhy7fLW47t3qK
    OLM0QBj4wL71I+k2BSMkCf1dyfqnITGI3jCbCFE6eKmF15Top1xcyN0sEx1SRnLe
    klE8uQsonJumvm7N308Ca2zteqWtlErLfEte
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
  labels:
    configVersion: "0.1"
    name: argocd-cert-config
  name: argocd-cert-config
  namespace: argocd